// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace DMAnaliseSentimentoML.Model
{
    public class ModelInput
    {
        [ColumnName("Predicado"), LoadColumn(0)]
        public bool Predicado { get; set; }

        [ColumnName("Texto"), LoadColumn(1)]
        public string Texto { get; set; }
    }
}
